version: '3.5'
services:
  clickhouse-keeper-01:
    container_name: clickhouse-keeper01
    image: clickhouse/clickhouse-keeper:latest
    hostname: keeper-server1.localdomain
    volumes:
      - ./keeper1.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - 9181:9181
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.15
  clickhouse-keeper-02:
    container_name: clickhouse-keeper02
    image: clickhouse/clickhouse-keeper:latest
    hostname: keeper-server2.localdomain
    volumes:
      - ./keeper2.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - 8181:9181
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.16
  clickhouse-keeper-03:
    container_name: clickhouse-keeper03
    image: clickhouse/clickhouse-keeper:latest
    hostname: keeper-server3.localdomain
    volumes:
      - ./keeper1.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - 7181:9181
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.17
  clickhouse01:
    image: clickhouse/clickhouse-server:23.2
    container_name: clickhouse01
    hostname: clickhouse01
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macro1.xml:/etc/clickhouse-server/config.d/macro.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
  clickhouse02:
    image: clickhouse/clickhouse-server:23.2
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macro2.xml:/etc/clickhouse-server/config.d/macro.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
  clickhouse03:
    image: clickhouse/clickhouse-server:23.2
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macro3.xml:/etc/clickhouse-server/config.d/macro.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
  clickhouse04:
    image: clickhouse/clickhouse-server:23.2
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macro4.xml:/etc/clickhouse-server/config.d/macro.xml
      - ./users.xml:/etc/clickhouse-server/users.xml

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/16
