version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
  clickhouse01:
    image: clickhouse/clickhouse-server:23.2
    container_name: clickhouse01
    hostname: clickhouse01
    volumes:
      - ./config1.xml:/etc/clickhouse-server/config.d/local.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:23.2
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - ./config2.xml:/etc/clickhouse-server/config.d/local.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
    depends_on:
      - zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server:23.2
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    volumes:
      - ./config3.xml:/etc/clickhouse-server/config.d/local.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
    depends_on:
      - zookeeper
  clickhouse04:
    image: clickhouse/clickhouse-server:23.2
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    volumes:
      - ./config4.xml:/etc/clickhouse-server/config.d/local.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
